#!/usr/bin/env python3
"""Install the CI workflow into the place GitHub looks for it.

The workflow lives at ``.github/ci/ci.yml`` because the automation identity
that produced this tree is not allowed to write under ``.github/workflows/``:
GitHub refuses the push with

    refusing to allow a GitHub App to create or update workflow
    `.github/workflows/ci.yml` without `workflows` permission

That is a permission on the token, not a problem with the file, and it is the
one step in this repository that a person with repository rights has to run
once. Everything else -- tests, checks, the release contract -- runs from a
plain checkout.

    python3 tools/install_ci.py            # install
    python3 tools/install_ci.py --check    # is the installed copy current?
    python3 tools/install_ci.py --selftest # check the installer itself

``--check`` exits non-zero when the installed workflow is missing or differs
from the source, so CI can fail when someone edits the installable copy and
forgets to reinstall -- which is how a "documented" workflow and a running
workflow drift apart.
"""
from __future__ import annotations

import argparse
import filecmp
import hashlib
import shutil
import sys
from pathlib import Path

SOURCE = Path(".github/ci/ci.yml")
INSTALLED = Path(".github/workflows/ci.yml")

BANNER = (
    "# Generated by tools/install_ci.py from .github/ci/ci.yml -- do not edit\n"
    "# this copy. Edit the source file and reinstall.\n"
)


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def install(root: Path = Path("."), quiet: bool = False) -> int:
    source = root / SOURCE
    target = root / INSTALLED
    if not source.is_file():
        print(f"FAIL  the workflow source is missing: {SOURCE}")
        return 1
    target.parent.mkdir(parents=True, exist_ok=True)
    body = source.read_text(encoding="utf-8")
    if body.startswith("# Generated by tools/install_ci.py"):
        body = "\n".join(body.splitlines()[2:]).lstrip("\n")
    target.write_text(BANNER + body, encoding="utf-8")
    if not quiet:
        print(f"OK    installed {SOURCE} -> {INSTALLED} ({len(body)} bytes)")
    return 0


def check(root: Path = Path("."), quiet: bool = False) -> int:
    source = root / SOURCE
    target = root / INSTALLED
    if not source.is_file():
        print(f"FAIL  the workflow source is missing: {SOURCE}")
        return 1
    if not target.is_file():
        print(f"WARN  {INSTALLED} is not present; run python3 tools/install_ci.py")
        return 0
    expected = BANNER + source.read_text(encoding="utf-8")
    actual = target.read_text(encoding="utf-8")
    if actual.strip() != expected.strip():
        print(f"FAIL  {INSTALLED} differs from {SOURCE}; reinstall it")
        return 1
    if not quiet:
        print(f"OK    {INSTALLED} matches {SOURCE}")
    return 0


def selftest() -> int:
    import tempfile

    failures = 0
    with tempfile.TemporaryDirectory() as temporary:
        root = Path(temporary)
        (root / SOURCE).parent.mkdir(parents=True)
        (root / SOURCE).write_text("name: CI\n", encoding="utf-8")

        if install(root, quiet=True) != 0:
            print("FAIL  a plain install should succeed")
            failures += 1
        installed = (root / INSTALLED).read_text(encoding="utf-8")
        if not installed.startswith(BANNER):
            print("FAIL  the installed copy must carry the do-not-edit banner")
            failures += 1
        if check(root, quiet=True) != 0:
            print("FAIL  a fresh install should pass --check")
            failures += 1
        if install(root, quiet=True) != 0 or check(root, quiet=True) != 0:
            print("FAIL  installing twice must be idempotent")
            failures += 1

        (root / INSTALLED).write_text("name: edited\n", encoding="utf-8")
        if check(root, quiet=True) == 0:
            print("FAIL  an edited installed copy must fail --check")
            failures += 1

        (root / SOURCE).unlink()
        if install(root, quiet=True) == 0 or check(root, quiet=True) == 0:
            print("FAIL  a missing source must fail both modes")
            failures += 1

    if failures:
        print(f"SELFTEST FAILED: {failures} case(s)")
        return 1
    print("SELFTEST OK: install, idempotence, drift detection, missing source")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="verify the installed copy is current")
    parser.add_argument("--selftest", action="store_true", help="check this script itself")
    arguments = parser.parse_args()
    if arguments.selftest:
        return selftest()
    if arguments.check:
        return check()
    return install()


if __name__ == "__main__":
    sys.exit(main())
